# Generated by Django 4.0.7 on 2023-02-17 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=200)),
                ('creationDateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='created on')),
                ('releaseDateTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='released on')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
